// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace StopSound.Migrations
{
    [DbContext(typeof(PluginDbContext))]
    [Migration("20250415223826_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("PlayerRecord", b =>
                {
                    b.Property<ulong>("SteamId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("steamid");

                    b.Property<int>("Kills")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kills");

                    b.HasKey("SteamId");

                    b.ToTable("players");
                });
#pragma warning restore 612, 618
        }
    }
}
