// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PluginStatTracking.Migrations
{
    [DbContext(typeof(PluginDbContext))]
    partial class PluginDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("PlayerRecord", b =>
                {
                    b.Property<ulong>("SteamId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("steamid");

                    b.Property<int>("Kills")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kills");

                    b.Property<string>("PlayerName")
                        .HasColumnType("TEXT")
                        .HasColumnName("playername");

                    b.HasKey("SteamId");

                    b.ToTable("players");
                });
#pragma warning restore 612, 618
        }
    }
}
